### ISSUE TITLE
Mac  安装的时候出现加载不了文件 ，说是class不能够赋值

### ISSUE THREAD

**Issue by steadyliu** [imouou/BUI-Fast-Snippets#3]
/.atom/snippets.cson: keyword 'class' can't be assigned

**Comment by imouou** [comment]
已经更新,请重新下载

**Comment by steadyliu** [comment]
> 已经更新,请重新下载

请问有QQ群么 ，想学习下

**Comment by imouou** [comment]
Q群: 691560280 或者去官网学习 www.easybui.com
